apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../crd
- ../rbac
- ../webhook

patchesStrategicMerge:
- mutating-webhook-loopback.yaml
- validating-webhook-loopback.yaml
- webhook-service-delete.yaml
