// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Owner struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstallationId string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	NodeId         string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Uid            string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Owner) Reset() {
	*x = Owner{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Owner) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *Owner) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Owner) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type Mutation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor  uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	Owner          *Owner                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Generation     uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Mutation) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *Mutation) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Mutation) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Mutation) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HealthRequest) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

type Capabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor       uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	NodeId              string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CloudHypervisor     string                 `protobuf:"bytes,3,opt,name=cloud_hypervisor,json=cloudHypervisor,proto3" json:"cloud_hypervisor,omitempty"`
	K8NetdProtocolMajor uint32                 `protobuf:"varint,4,opt,name=k8netd_protocol_major,json=k8netdProtocolMajor,proto3" json:"k8netd_protocol_major,omitempty"`
	CanUseKvm           bool                   `protobuf:"varint,5,opt,name=can_use_kvm,json=canUseKvm,proto3" json:"can_use_kvm,omitempty"`
	CanUseUserDbus      bool                   `protobuf:"varint,6,opt,name=can_use_user_dbus,json=canUseUserDbus,proto3" json:"can_use_user_dbus,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Capabilities) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *Capabilities) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Capabilities) GetCloudHypervisor() string {
	if x != nil {
		return x.CloudHypervisor
	}
	return ""
}

func (x *Capabilities) GetK8NetdProtocolMajor() uint32 {
	if x != nil {
		return x.K8NetdProtocolMajor
	}
	return 0
}

func (x *Capabilities) GetCanUseKvm() bool {
	if x != nil {
		return x.CanUseKvm
	}
	return false
}

func (x *Capabilities) GetCanUseUserDbus() bool {
	if x != nil {
		return x.CanUseUserDbus
	}
	return false
}

type VMDesired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Firmware      string                 `protobuf:"bytes,4,opt,name=firmware,proto3" json:"firmware,omitempty"`
	ApiSocket     string                 `protobuf:"bytes,5,opt,name=api_socket,json=apiSocket,proto3" json:"api_socket,omitempty"`
	VhostSocket   string                 `protobuf:"bytes,6,opt,name=vhost_socket,json=vhostSocket,proto3" json:"vhost_socket,omitempty"`
	Disk          string                 `protobuf:"bytes,7,opt,name=disk,proto3" json:"disk,omitempty"`
	Mac           string                 `protobuf:"bytes,8,opt,name=mac,proto3" json:"mac,omitempty"`
	Ip            string                 `protobuf:"bytes,9,opt,name=ip,proto3" json:"ip,omitempty"`
	Cpus          uint32                 `protobuf:"varint,10,opt,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryMib     uint32                 `protobuf:"varint,11,opt,name=memory_mib,json=memoryMib,proto3" json:"memory_mib,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMDesired) Reset() {
	*x = VMDesired{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMDesired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMDesired) ProtoMessage() {}

func (x *VMDesired) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMDesired.ProtoReflect.Descriptor instead.
func (*VMDesired) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *VMDesired) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *VMDesired) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VMDesired) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *VMDesired) GetFirmware() string {
	if x != nil {
		return x.Firmware
	}
	return ""
}

func (x *VMDesired) GetApiSocket() string {
	if x != nil {
		return x.ApiSocket
	}
	return ""
}

func (x *VMDesired) GetVhostSocket() string {
	if x != nil {
		return x.VhostSocket
	}
	return ""
}

func (x *VMDesired) GetDisk() string {
	if x != nil {
		return x.Disk
	}
	return ""
}

func (x *VMDesired) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *VMDesired) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *VMDesired) GetCpus() uint32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *VMDesired) GetMemoryMib() uint32 {
	if x != nil {
		return x.MemoryMib
	}
	return 0
}

type VMObserved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Pid           int64                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	GuestUptime   uint64                 `protobuf:"varint,4,opt,name=guest_uptime,json=guestUptime,proto3" json:"guest_uptime,omitempty"`
	Running       bool                   `protobuf:"varint,5,opt,name=running,proto3" json:"running,omitempty"`
	ApiSocket     string                 `protobuf:"bytes,6,opt,name=api_socket,json=apiSocket,proto3" json:"api_socket,omitempty"`
	VhostSocket   string                 `protobuf:"bytes,7,opt,name=vhost_socket,json=vhostSocket,proto3" json:"vhost_socket,omitempty"`
	Ip            string                 `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac           string                 `protobuf:"bytes,9,opt,name=mac,proto3" json:"mac,omitempty"`
	Generation    uint64                 `protobuf:"varint,10,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMObserved) Reset() {
	*x = VMObserved{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMObserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMObserved) ProtoMessage() {}

func (x *VMObserved) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMObserved.ProtoReflect.Descriptor instead.
func (*VMObserved) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *VMObserved) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *VMObserved) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *VMObserved) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *VMObserved) GetGuestUptime() uint64 {
	if x != nil {
		return x.GuestUptime
	}
	return 0
}

func (x *VMObserved) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *VMObserved) GetApiSocket() string {
	if x != nil {
		return x.ApiSocket
	}
	return ""
}

func (x *VMObserved) GetVhostSocket() string {
	if x != nil {
		return x.VhostSocket
	}
	return ""
}

func (x *VMObserved) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *VMObserved) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *VMObserved) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type EnsureVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutation      *Mutation              `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	Desired       *VMDesired             `protobuf:"bytes,2,opt,name=desired,proto3" json:"desired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureVMRequest) Reset() {
	*x = EnsureVMRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureVMRequest) ProtoMessage() {}

func (x *EnsureVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureVMRequest.ProtoReflect.Descriptor instead.
func (*EnsureVMRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *EnsureVMRequest) GetMutation() *Mutation {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *EnsureVMRequest) GetDesired() *VMDesired {
	if x != nil {
		return x.Desired
	}
	return nil
}

type GetVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         *Owner                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	ProtocolMajor uint32                 `protobuf:"varint,2,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMRequest) Reset() {
	*x = GetVMRequest{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMRequest) ProtoMessage() {}

func (x *GetVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMRequest.ProtoReflect.Descriptor instead.
func (*GetVMRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetVMRequest) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *GetVMRequest) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

type VMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observed      *VMObserved            `protobuf:"bytes,1,opt,name=observed,proto3" json:"observed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMResponse) Reset() {
	*x = VMResponse{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMResponse) ProtoMessage() {}

func (x *VMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMResponse.ProtoReflect.Descriptor instead.
func (*VMResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *VMResponse) GetObserved() *VMObserved {
	if x != nil {
		return x.Observed
	}
	return nil
}

type MutationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutation      *Mutation              `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationRequest) Reset() {
	*x = MutationRequest{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationRequest) ProtoMessage() {}

func (x *MutationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationRequest.ProtoReflect.Descriptor instead.
func (*MutationRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *MutationRequest) GetMutation() *Mutation {
	if x != nil {
		return x.Mutation
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x0fk8labs.agent.v1\"[\n" +
	"\x05Owner\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\tR\x0einstallationId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\"\xa8\x01\n" +
	"\bMutation\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x12,\n" +
	"\x05owner\x18\x02 \x01(\v2\x16.k8labs.agent.v1.OwnerR\x05owner\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"6\n" +
	"\rHealthRequest\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\"\xf8\x01\n" +
	"\fCapabilities\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12)\n" +
	"\x10cloud_hypervisor\x18\x03 \x01(\tR\x0fcloudHypervisor\x122\n" +
	"\x15k8netd_protocol_major\x18\x04 \x01(\rR\x13k8netdProtocolMajor\x12\x1e\n" +
	"\vcan_use_kvm\x18\x05 \x01(\bR\tcanUseKvm\x12)\n" +
	"\x11can_use_user_dbus\x18\x06 \x01(\bR\x0ecanUseUserDbus\"\x8e\x02\n" +
	"\tVMDesired\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1a\n" +
	"\bfirmware\x18\x04 \x01(\tR\bfirmware\x12\x1d\n" +
	"\n" +
	"api_socket\x18\x05 \x01(\tR\tapiSocket\x12!\n" +
	"\fvhost_socket\x18\x06 \x01(\tR\vvhostSocket\x12\x12\n" +
	"\x04disk\x18\a \x01(\tR\x04disk\x12\x10\n" +
	"\x03mac\x18\b \x01(\tR\x03mac\x12\x0e\n" +
	"\x02ip\x18\t \x01(\tR\x02ip\x12\x12\n" +
	"\x04cpus\x18\n" +
	" \x01(\rR\x04cpus\x12\x1d\n" +
	"\n" +
	"memory_mib\x18\v \x01(\rR\tmemoryMib\"\x85\x02\n" +
	"\n" +
	"VMObserved\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x03R\x03pid\x12!\n" +
	"\fguest_uptime\x18\x04 \x01(\x04R\vguestUptime\x12\x18\n" +
	"\arunning\x18\x05 \x01(\bR\arunning\x12\x1d\n" +
	"\n" +
	"api_socket\x18\x06 \x01(\tR\tapiSocket\x12!\n" +
	"\fvhost_socket\x18\a \x01(\tR\vvhostSocket\x12\x0e\n" +
	"\x02ip\x18\b \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\t \x01(\tR\x03mac\x12\x1e\n" +
	"\n" +
	"generation\x18\n" +
	" \x01(\x04R\n" +
	"generation\"~\n" +
	"\x0fEnsureVMRequest\x125\n" +
	"\bmutation\x18\x01 \x01(\v2\x19.k8labs.agent.v1.MutationR\bmutation\x124\n" +
	"\adesired\x18\x02 \x01(\v2\x1a.k8labs.agent.v1.VMDesiredR\adesired\"c\n" +
	"\fGetVMRequest\x12,\n" +
	"\x05owner\x18\x01 \x01(\v2\x16.k8labs.agent.v1.OwnerR\x05owner\x12%\n" +
	"\x0eprotocol_major\x18\x02 \x01(\rR\rprotocolMajor\"E\n" +
	"\n" +
	"VMResponse\x127\n" +
	"\bobserved\x18\x01 \x01(\v2\x1b.k8labs.agent.v1.VMObservedR\bobserved\"H\n" +
	"\x0fMutationRequest\x125\n" +
	"\bmutation\x18\x01 \x01(\v2\x19.k8labs.agent.v1.MutationR\bmutation\"\a\n" +
	"\x05Empty2\xee\x02\n" +
	"\tHostAgent\x12G\n" +
	"\x06Health\x12\x1e.k8labs.agent.v1.HealthRequest\x1a\x1d.k8labs.agent.v1.Capabilities\x12I\n" +
	"\bEnsureVM\x12 .k8labs.agent.v1.EnsureVMRequest\x1a\x1b.k8labs.agent.v1.VMResponse\x12C\n" +
	"\x05GetVM\x12\x1d.k8labs.agent.v1.GetVMRequest\x1a\x1b.k8labs.agent.v1.VMResponse\x12B\n" +
	"\x06StopVM\x12 .k8labs.agent.v1.MutationRequest\x1a\x16.k8labs.agent.v1.Empty\x12D\n" +
	"\bDeleteVM\x12 .k8labs.agent.v1.MutationRequest\x1a\x16.k8labs.agent.v1.EmptyBDZBgithub.com/moeryomenko/cluster-api-hypervisor/api/agent/v1;agentv1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_agent_proto_goTypes = []any{
	(*Owner)(nil),           // 0: k8labs.agent.v1.Owner
	(*Mutation)(nil),        // 1: k8labs.agent.v1.Mutation
	(*HealthRequest)(nil),   // 2: k8labs.agent.v1.HealthRequest
	(*Capabilities)(nil),    // 3: k8labs.agent.v1.Capabilities
	(*VMDesired)(nil),       // 4: k8labs.agent.v1.VMDesired
	(*VMObserved)(nil),      // 5: k8labs.agent.v1.VMObserved
	(*EnsureVMRequest)(nil), // 6: k8labs.agent.v1.EnsureVMRequest
	(*GetVMRequest)(nil),    // 7: k8labs.agent.v1.GetVMRequest
	(*VMResponse)(nil),      // 8: k8labs.agent.v1.VMResponse
	(*MutationRequest)(nil), // 9: k8labs.agent.v1.MutationRequest
	(*Empty)(nil),           // 10: k8labs.agent.v1.Empty
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: k8labs.agent.v1.Mutation.owner:type_name -> k8labs.agent.v1.Owner
	1,  // 1: k8labs.agent.v1.EnsureVMRequest.mutation:type_name -> k8labs.agent.v1.Mutation
	4,  // 2: k8labs.agent.v1.EnsureVMRequest.desired:type_name -> k8labs.agent.v1.VMDesired
	0,  // 3: k8labs.agent.v1.GetVMRequest.owner:type_name -> k8labs.agent.v1.Owner
	5,  // 4: k8labs.agent.v1.VMResponse.observed:type_name -> k8labs.agent.v1.VMObserved
	1,  // 5: k8labs.agent.v1.MutationRequest.mutation:type_name -> k8labs.agent.v1.Mutation
	2,  // 6: k8labs.agent.v1.HostAgent.Health:input_type -> k8labs.agent.v1.HealthRequest
	6,  // 7: k8labs.agent.v1.HostAgent.EnsureVM:input_type -> k8labs.agent.v1.EnsureVMRequest
	7,  // 8: k8labs.agent.v1.HostAgent.GetVM:input_type -> k8labs.agent.v1.GetVMRequest
	9,  // 9: k8labs.agent.v1.HostAgent.StopVM:input_type -> k8labs.agent.v1.MutationRequest
	9,  // 10: k8labs.agent.v1.HostAgent.DeleteVM:input_type -> k8labs.agent.v1.MutationRequest
	3,  // 11: k8labs.agent.v1.HostAgent.Health:output_type -> k8labs.agent.v1.Capabilities
	8,  // 12: k8labs.agent.v1.HostAgent.EnsureVM:output_type -> k8labs.agent.v1.VMResponse
	8,  // 13: k8labs.agent.v1.HostAgent.GetVM:output_type -> k8labs.agent.v1.VMResponse
	10, // 14: k8labs.agent.v1.HostAgent.StopVM:output_type -> k8labs.agent.v1.Empty
	10, // 15: k8labs.agent.v1.HostAgent.DeleteVM:output_type -> k8labs.agent.v1.Empty
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
