//go:build !ignore_autogenerated

/*
Copyright 2026 The cluster-api-hypervisor Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package controlplanev1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneInitializationStatus) DeepCopyInto(out *ControlPlaneInitializationStatus) {
	*out = *in
	if in.ControlPlaneInitialized != nil {
		in, out := &in.ControlPlaneInitialized, &out.ControlPlaneInitialized
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneInitializationStatus.
func (in *ControlPlaneInitializationStatus) DeepCopy() *ControlPlaneInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneReplacementStatus) DeepCopyInto(out *ControlPlaneReplacementStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneReplacementStatus.
func (in *ControlPlaneReplacementStatus) DeepCopy() *ControlPlaneReplacementStatus {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneReplacementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorControlPlane) DeepCopyInto(out *HypervisorControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorControlPlane.
func (in *HypervisorControlPlane) DeepCopy() *HypervisorControlPlane {
	if in == nil {
		return nil
	}
	out := new(HypervisorControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HypervisorControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorControlPlaneList) DeepCopyInto(out *HypervisorControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HypervisorControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorControlPlaneList.
func (in *HypervisorControlPlaneList) DeepCopy() *HypervisorControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(HypervisorControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HypervisorControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorControlPlaneMachineTemplate) DeepCopyInto(out *HypervisorControlPlaneMachineTemplate) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorControlPlaneMachineTemplate.
func (in *HypervisorControlPlaneMachineTemplate) DeepCopy() *HypervisorControlPlaneMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(HypervisorControlPlaneMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorControlPlaneMachineTemplateSpec) DeepCopyInto(out *HypervisorControlPlaneMachineTemplateSpec) {
	*out = *in
	out.InfrastructureRef = in.InfrastructureRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorControlPlaneMachineTemplateSpec.
func (in *HypervisorControlPlaneMachineTemplateSpec) DeepCopy() *HypervisorControlPlaneMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(HypervisorControlPlaneMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorControlPlaneResource) DeepCopyInto(out *HypervisorControlPlaneResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorControlPlaneResource.
func (in *HypervisorControlPlaneResource) DeepCopy() *HypervisorControlPlaneResource {
	if in == nil {
		return nil
	}
	out := new(HypervisorControlPlaneResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorControlPlaneSpec) DeepCopyInto(out *HypervisorControlPlaneSpec) {
	*out = *in
	in.MachineTemplate.DeepCopyInto(&out.MachineTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorControlPlaneSpec.
func (in *HypervisorControlPlaneSpec) DeepCopy() *HypervisorControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(HypervisorControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorControlPlaneStatus) DeepCopyInto(out *HypervisorControlPlaneStatus) {
	*out = *in
	in.Initialization.DeepCopyInto(&out.Initialization)
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Replacement != nil {
		in, out := &in.Replacement, &out.Replacement
		*out = new(ControlPlaneReplacementStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorControlPlaneStatus.
func (in *HypervisorControlPlaneStatus) DeepCopy() *HypervisorControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(HypervisorControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorControlPlaneTemplate) DeepCopyInto(out *HypervisorControlPlaneTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorControlPlaneTemplate.
func (in *HypervisorControlPlaneTemplate) DeepCopy() *HypervisorControlPlaneTemplate {
	if in == nil {
		return nil
	}
	out := new(HypervisorControlPlaneTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HypervisorControlPlaneTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorControlPlaneTemplateList) DeepCopyInto(out *HypervisorControlPlaneTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HypervisorControlPlaneTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorControlPlaneTemplateList.
func (in *HypervisorControlPlaneTemplateList) DeepCopy() *HypervisorControlPlaneTemplateList {
	if in == nil {
		return nil
	}
	out := new(HypervisorControlPlaneTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HypervisorControlPlaneTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorControlPlaneTemplateSpec) DeepCopyInto(out *HypervisorControlPlaneTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorControlPlaneTemplateSpec.
func (in *HypervisorControlPlaneTemplateSpec) DeepCopy() *HypervisorControlPlaneTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(HypervisorControlPlaneTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorUpgradePlan) DeepCopyInto(out *HypervisorUpgradePlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorUpgradePlan.
func (in *HypervisorUpgradePlan) DeepCopy() *HypervisorUpgradePlan {
	if in == nil {
		return nil
	}
	out := new(HypervisorUpgradePlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HypervisorUpgradePlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorUpgradePlanList) DeepCopyInto(out *HypervisorUpgradePlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HypervisorUpgradePlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorUpgradePlanList.
func (in *HypervisorUpgradePlanList) DeepCopy() *HypervisorUpgradePlanList {
	if in == nil {
		return nil
	}
	out := new(HypervisorUpgradePlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HypervisorUpgradePlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorUpgradePlanSpec) DeepCopyInto(out *HypervisorUpgradePlanSpec) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorUpgradePlanSpec.
func (in *HypervisorUpgradePlanSpec) DeepCopy() *HypervisorUpgradePlanSpec {
	if in == nil {
		return nil
	}
	out := new(HypervisorUpgradePlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorUpgradePlanStatus) DeepCopyInto(out *HypervisorUpgradePlanStatus) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]UpgradeStepStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorUpgradePlanStatus.
func (in *HypervisorUpgradePlanStatus) DeepCopy() *HypervisorUpgradePlanStatus {
	if in == nil {
		return nil
	}
	out := new(HypervisorUpgradePlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeStepStatus) DeepCopyInto(out *UpgradeStepStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeStepStatus.
func (in *UpgradeStepStatus) DeepCopy() *UpgradeStepStatus {
	if in == nil {
		return nil
	}
	out := new(UpgradeStepStatus)
	in.DeepCopyInto(out)
	return out
}
